In [10]:
import numpy as np

In [16]:
vec1 = np.array((1,2,2)) # array of the type int64
print (vec1)

[1 2 2]


In [18]:
vec2 = np.array((1.0,2.0,3.0)) # float
print (vec2)

[1. 2. 3.]


In [20]:
vec3 = np.array((1,2,3), dtype = float)
print(vec3)

[1. 2. 3.]


In [21]:
mat1 = np.array(((1,2,3),
                 (4,5,6),
                 (6,7,8)))
print (mat1)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [23]:
mat3 = np.zeros((3,4))
mat3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
mat4 = np.ones((3,4))
mat4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
mat5 = np.empty((3,4))
print (mat5)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
mat6 = np.random.rand (3,4)
print (mat6)

[[0.61994703 0.24693316 0.70345831 0.54314854]
 [0.83272637 0.6419255  0.8008702  0.43640894]
 [0.20305643 0.35783965 0.80140762 0.77729569]]


In [29]:
mat7 = np.eye(3)
print (mat7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
vec4 = np.arange(10,20,2)
print (vec4)

[10 12 14 16 18]


In [32]:
vec5 = np.linspace(1,2,5)
print (vec5)

[1.   1.25 1.5  1.75 2.  ]


In [34]:
print (mat1[1,2])

6


In [35]:
mat1b = mat1[1:]
mat1b

array([[4, 5, 6],
       [6, 7, 8]])

In [36]:
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [37]:
mat2b = mat1[2:]
mat2b

array([[6, 7, 8]])

In [39]:
mat1c = mat1[:,:2]
mat1c

array([[1, 2],
       [4, 5],
       [6, 7]])

In [42]:
mat1b[1,1] = -78
mat1b

array([[  4,   5,   6],
       [-77, -78, -77]])

In [44]:
mat1d = mat1[1,:].copy()
mat1d

array([4, 5, 6])

In [47]:
mat5 = np.array(((1,2),(3,4)), dtype=float)
mat6 = np.array(((2,3), (-1,9)), dtype = float)

In [48]:
print(mat5+mat6)

[[ 3.  5.]
 [ 2. 13.]]


In [49]:
print(mat5*mat6)

[[ 2.  6.]
 [-3. 36.]]


In [51]:
print(mat5.dot(mat6))

[[ 0. 21.]
 [ 2. 45.]]
