In [1]:
import numpy as np
from scipy import linalg

In [18]:
a = np.array(((1,2),(3,4)))
ainv = linalg.inv(a)
print(ainv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [19]:
b = np.array((8,18))
x = linalg.solve (a,b)
x

array([2., 3.])

In [5]:
print(linalg.det(a))

-2.0


In [7]:
print(linalg.norm(a))

5.477225575051661


In [8]:
print(linalg.norm(a,1))

6.0


In [9]:
print(linalg.norm(a, np.inf))

7.0


In [10]:
print(linalg.norm(a, "fro"))

5.477225575051661


In [20]:
c,x = linalg.eig(a)
print(c)
print(x)

[-0.37228132+0.j  5.37228132+0.j]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [22]:
x= np.linalg.solve(a,b)
print (x)

[2. 3.]


In [24]:
x = linalg.solve(a,b)
x

array([2., 3.])

In [26]:
lu, piv, x, info = linalg.lapack.dgesv(a,b)

In [27]:
print(lu)

[[3.         4.        ]
 [0.33333333 0.66666667]]


In [28]:
print(piv)

[1 1]


In [29]:
print(x)

[2. 3.]


In [30]:
print(info)

0
